### ISSUE TITLE
Compatibility Python 3.11

### ISSUE THREAD

**Issue by DamyanBG** [amitdev/lru-dict#44]
I have problem when I am trying to install lru-dict on Python 3.11:

Failed to build lru-dict
Installing collected packages: lru-dict
  Running setup.py install for lru-dict ... error
  error: subprocess-exited-with-error

  × Running setup.py install for lru-dict did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      running install
      \.venv\Lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_ext
      building 'lru' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> lru-dict

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by mgiessing** [comment]
@AndreMiras @amitdev 
Can you estimate when the next version is released to support Python 3.11 as well as ppc64le architecture?

Thanks a lot! :-)

**Comment by AndreMiras** [comment]
Hi @mgiessing, thanks for the heads up.
Yes we just need to have https://github.com/amitdev/lru-dict/pull/43 merged (since it bumps cibuildwheel) and a new tag push, CI would do the rest, but I don't have write access to the repository.
@amitdev would you like to look this up? Basically the PR mentioned above would add 3.11 support to prebuilt wheels and then we already have the ppc architecture merged so pushing a tag would get both covered.

**Comment by fhenneke** [comment]
Would it be possible to tag a new release? It sounds like the code is compatible with Python 3.11 but that version is not officially supported yet.

**Comment by amitdev** [comment]
Sorry for the delay on this. The new version should work with 3.11.
